---
title: 'Data Science: Machine Learning - HarvardX: PH125.8x'
author: 'Luiz Cunha'
date: '2019-08-15'
output: html_notebook
---

# Introduction and Welcome

## Welcome to Data Science: Machine Learning

Welcome to **Data Science: Machine Learning!** We're excited to have you join us in this course, which is designed to teach you the basics of machine learning, the science behind the most popular and successful data science techniques, by learning to build a movie recommendation system.

Perhaps the most popular data science methodologies come from machine learning. What distinguishes machine learning from other computer guided decision processes is that it builds prediction algorithms using data. Some of the most popular products that use machine learning include the handwriting readers implemented by the postal service, speech recognition, movie recommendation systems, and spam detectors. 

In this course, you will learn popular machine learning algorithms, principal component analysis, and regularization by building a movie recommendation system. You will learn about training data, a set of data used to discover potentially predictive relationships, and how the data can come in the form of the outcome we want to predict and features that we will use to predict this outcome. As you build the movie recommendation system, you will learn how to train algorithms using training data so you can predict the outcome for future datasets. You will also learn about overtraining and techniques to avoid it such as cross-validation. All of these skills are fundamental to machine learning.

The class notes for this course series can be found in Professor Irizarry's freely available Introduction to Data Science book.

**In this course, you will learn:**

* The basics of machine learning
* How to perform cross-validation to avoid overtraining
* Several popular machine learning algorithms
* How to build a recommendation system
* What regularization is and why it is useful

### Course overview

There are six major sections in this course: introduction to machine learning; machine learning basics; linear regression for prediction, smoothing, and working with matrices; distance, knn, cross validation, and generative models; classification with more than two classes and the caret package; and model fitting and recommendation systems.

**Section1: Introduction to Machine Learning**

In this section, you'll be introduced to some of the terminology and concepts you'll need going forward.

**Section 2: Machine Learning Basics**

In this section, you'll learn how to start building a machine learning algorithm using training and test data sets and the importance of conditional probabilities for machine learning.

**Section 3: Linear Regression for Prediction, Smoothing, and Working with Matrices**

In this section, you'll learn why linear regression is a useful baseline approach but is often insufficiently flexible for more complex analyses, how to smooth noisy data, and how to use matrices for machine learning.

**Section 4: Distance, Knn, Cross Validation, and Generative Models**

In this section, you'll learn different types of discriminative and generative approaches for machine learning algorithms.

**Section 5: Classification with More than Two Classes and the Caret Package**

In this section, you'll learn how to overcome the curse of dimensionality using methods that adapt to higher dimensions and how to use the caret package to implement many different machine learning algorithms.

**Section 6: Model Fitting and Recommendation Systems**

In this section, you'll learn how to apply the machine learning algorithms you have learned.
